#language: go

#go:
#  - 1.13.x

# branches restriction
#
# Travis has two build types: branch & pull request builds. Both are turned on
# by default, meaning that if you don't include this restriction or disable
# either build type in the Travis settings panel, two jobs will be run for each
# commit in a pull request. If you do include this restriction, it means that
# the entire build will not be started if the branch is not main, or if the
# pull request doesn't point to main.
#
# Pull request builds are useful because they skip deploy section of this yaml,
# branch builds are necessary because they are the only way to run a build on
# main.
#
# In summary, the restriction below will only allow Travis to build for:
# - main branch
# - pull requests with merge base set to main

branches:
  only:
    - master

env:
  global:
    - VERSION=${TRAVIS_BUILD_NUMBER}
    - BRANCH=${TRAVIS_BRANCH}

before_install:
  - docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD} ${DOCKER_REGISTRY}

# install stage
#
# The build will run the commands below in sequence.
# If one command fails:
# - the build stops immediately
# - the build results in a failure

install:
  - git config --global --add url."https://${GH_TOKEN}@github.com/Typeform/".insteadOf "https://github.com/Typeform/"

# script stage
#
# The build will run the commands below in sequence.
# If one command fails:
# - the build *continues* until all commands are executed
# - the build results in a failure
#
# References:
# - https://docs.travis-ci.com/user/job-lifecycle/#customizing-the-build-phase

script:
  - make build
  - make test

# deploy stage
#
# This part of the build will be skipped for:
# - builds that have failed in the script stage
# - pull requests
#
# References:
# - https://docs.travis-ci.com/user/deployment#pull-requests
# - https://docs.travis-ci.com/user/job-lifecycle/#deploying-your-code

#deploy:
#  provider: script
#  script:
#    - make push-latest && make deploy
#  on:
#    branch: master
