foo-access-key: "foo"
bar-access-key: 'foo'
baz-access-key: foo
foo-secret-access-key: "bar"
bar-secret-access-key: 'bar'
baz-secret-access-key: bar
foo-credentials-secret: "foo-root-credentials-secret"
bar-credentials-secret: bar-root-credentials-secret
baz-credentials-secret: 'baz-root-credentials-secret'
FOO_ACCESS_KEY_ID: ${file(env.${env:ENVIRONMENT}.yml):foo-access-key}
FOO_SECRET_ACCESS_KEY: ${file(env.${env:ENVIRONMENT}.yml):foo-secret-access-key}
