name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  VERSION: ${GITHUB_RUN_ID}

jobs:
  build:
    name: Run tests and build
    runs-on: [self-hosted, bear]

    steps:

      - name: Build version
        run: echo ${{ env.VERSION }}
      
      - name: Registry login
        run: docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }} ${{ secrets.DOCKER_REGISTRY }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run unit tests for config generator
        run: make test-config-generator

      - name: Run integration tests (code samples) for global gitleaks config
        run: make test-gitleaks-config

      - name: Build image
        run: make build

      - name: Semantic Release
        id: semantic
        if: github.event_name == 'push'
        uses: codfish/semantic-release-action@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

       - name: Push version image
        if: steps.semantic.outputs.new-release-published == 'true'
        run: make push
        env:
          RELEASE_TAG: ${{ steps.semantic.outputs.release-version }}

      - name: Push latest images
        if: contains(github.ref, 'refs/heads/main')
        run: make push-latest
