name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  VERSION: ${GITHUB_RUN_ID}

jobs:
  build:
    name: Run tests, build, and publish if needed
    runs-on: [self-hosted, bear]

    steps:

      - name: Build version
        run: echo ${{ env.VERSION }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build image
        run: make build
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Run unit tests for config generator
        run: make test-config-generator
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Run integration tests (code samples) for global gitleaks config
        run: make test-gitleaks-config
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Semantic Release
        id: semantic
        if: github.event_name == 'push'
        uses: codfish/semantic-release-action@v1
        with:
          branches: |
            ['main']
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
          tag_format: '${version}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push versioned tagged image
        if: steps.semantic.outputs.new-release-published == 'true'
        run: make push
        env:
          RELEASE_TAG: ${{ steps.semantic.outputs.release-version }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Push latest-tagged image
        if: contains(github.ref, 'refs/heads/main')
        run: make push-latest
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
