name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  VERSION: ${GITHUB_RUN_ID}

jobs:
  build:
    name: Run tests and build
    runs-on: [self-hosted, bear-ephemeral]

    steps:

      - name: Build version
        run: echo ${{ env.VERSION }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build image
        run: make build
        env:
          CONTAINER_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Run unit tests for config generator
        run: make test-config-generator
        env:
          CONTAINER_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Run tests (code samples) for global gitleaks config
        run: make test-gitleaks-config
        env:
          CONTAINER_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Semantic Release
        id: semantic
        if: github.event_name == 'push'
        uses: codfish/semantic-release-action@v1
        with:
          branches: |
            ['main']
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
          tag_format: '${version}'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push versioned tagged image
        if: steps.semantic.outputs.new-release-published == 'true'
        run: make push
        env:
          RELEASE_TAG: ${{ steps.semantic.outputs.release-version }}
          CONTAINER_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      - name: Push latest-tagged image
        if: contains(github.ref, 'refs/heads/main')
        run: make push-latest
        env:
          CONTAINER_REGISTRY: ${{ secrets.ECR_REGISTRY }}

      # This is a temporary fix until SP-1665 is done
      - name: Push versioned tagged image to quay.io
        if: steps.semantic.outputs.new-release-published == 'true'
        run: make push-quay
        env:
          RELEASE_TAG: ${{ steps.semantic.outputs.release-version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push latest-tagged image to quay.io
        if: contains(github.ref, 'refs/heads/main')
        run: make push-latest-quay
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
