name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  VERSION: ${GITHUB_RUN_ID}

jobs:
  build:
    name: Run tests and releases if necessary
    runs-on: ubuntu-latest

    steps:

      - name: Build version
        run: echo ${{ env.VERSION }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Build image
        run: make build

      - name: Run unit tests for config generator
        run: make test-config-generator

      - name: Run tests (code samples) for global gitleaks config
        run: make test-gitleaks-config

      - name: Semantic Release
        id: semantic
        if: github.event_name == 'push'
        uses: codfish/semantic-release-action@v1
        with:
          branches: |
            ['main']
          plugins: |
            [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
          tag_format: '${version}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
