name: Synchronize Repository

on:
  workflow_dispatch:

jobs:
  sync_repo:
    name: Synchronize Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add remote upstream
        run: git remote add upstream https://github.com/Typeform/gitleaks-config-source.git

      - name: Pull and fetch from upstream
        run: |
          git pull upstream main
          git fetch upstream

      - name: Push updates and tags to origin
        run: |
          git push origin main
          git push --tags origin

